# Generated by Django 5.1.1 on 2024-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pruebas/', verbose_name='Imagen'),
        ),
    ]
